#!/bin/bash

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi


UNBOUND_PATH="/opt/unbound-dns"

$(which launchctl) stop /Library/LaunchAgents/yangliu.unbound-dns.updater.plist
$(which launchctl) stop /Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist
$(which launchctl) stop /Library/LaunchDaemons/homebrew.mxcl.unbound.plist

$(which launchctl) unload /Library/LaunchAgents/yangliu.unbound-dns.updater.plist
$(which launchctl) unload /Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist
$(which launchctl) unload /Library/LaunchDaemons/homebrew.mxcl.unbound.plist

rm /Library/LaunchAgents/yangliu.unbound-dns.updater.plist
rm /Library/LaunchDaemons/homebrew.mxcl.dnscrypt-proxy.plist
rm /Library/LaunchDaemons/homebrew.mxcl.unbound.plist

rm -rf $UNBOUND_PATH

# done
echo "Unbound and DNSCrypt-Proxy have been removed."
echo "Please set your DNS Server back to the original ones"

# open network preference panel
open /System/Library/PreferencePanes/Network.prefPane/